receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4319"
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: "jaeger:4317"  # send traces to jaeger inside docker network
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889" # expose metrics to Prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
