global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector-app-metrics' # Renamed for clarity
    static_configs:
      # Target the otel-collector service by its name, and its exposed app metrics port
      - targets: ['otel-collector:8889']

  - job_name: 'otel-collector-self-metrics' # Renamed for clarity
    static_configs:
      # Target the otel-collector service by its name, and its exposed internal metrics port
      - targets: ['otel-collector:8888']